package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Game;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    Game selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    List<Game> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    int updateByPrimaryKey(Game record);
}