package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Publisher;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PublisherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    int insert(Publisher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    Publisher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    List<Publisher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    int updateByPrimaryKey(Publisher record);
}