package lt.vu.mybatis.model;

import java.util.Date;
import java.util.List;

public class Publisher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.FOUNDED
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    private Date founded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.LOGO_LINK
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    private String logoLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.WEBSITE_LINK
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    private String websiteLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.ID
     *
     * @return the value of PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.ID
     *
     * @param id the value for PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.FOUNDED
     *
     * @return the value of PUBLIC.PUBLISHER.FOUNDED
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public Date getFounded() {
        return founded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.FOUNDED
     *
     * @param founded the value for PUBLIC.PUBLISHER.FOUNDED
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public void setFounded(Date founded) {
        this.founded = founded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.LOGO_LINK
     *
     * @return the value of PUBLIC.PUBLISHER.LOGO_LINK
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public String getLogoLink() {
        return logoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.LOGO_LINK
     *
     * @param logoLink the value for PUBLIC.PUBLISHER.LOGO_LINK
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public void setLogoLink(String logoLink) {
        this.logoLink = logoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.NAME
     *
     * @return the value of PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.NAME
     *
     * @param name the value for PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.WEBSITE_LINK
     *
     * @return the value of PUBLIC.PUBLISHER.WEBSITE_LINK
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public String getWebsiteLink() {
        return websiteLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.WEBSITE_LINK
     *
     * @param websiteLink the value for PUBLIC.PUBLISHER.WEBSITE_LINK
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public void setWebsiteLink(String websiteLink) {
        this.websiteLink = websiteLink;
    }

    private List<Game> publishedGames;

    public List<Game> getPublishedGames() { return publishedGames; }

    public void setPublishedGames(List<Game> publishedGames) { this.publishedGames = publishedGames; }
}