package lt.vu.mybatis.model;

import java.util.List;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.ID
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.USERNAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.ID
     *
     * @return the value of PUBLIC.USER.ID
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.ID
     *
     * @param id the value for PUBLIC.USER.ID
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.PASSWORD
     *
     * @return the value of PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.PASSWORD
     *
     * @param password the value for PUBLIC.USER.PASSWORD
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.USERNAME
     *
     * @return the value of PUBLIC.USER.USERNAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.USERNAME
     *
     * @param username the value for PUBLIC.USER.USERNAME
     *
     * @mbg.generated Mon Apr 06 12:40:26 EEST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    private List<Game> purchasedGames;

    public List<Game> getPurchasedGames() { return purchasedGames; }

    public void setPurchasedGames(List<Game> purchasedGames) {
        this.purchasedGames = purchasedGames;
    }
}