INSERT INTO PUBLIC.USER_GAME (USER_ID, GAME_ID) VALUES (2, 3);
INSERT INTO PUBLIC.USER_GAME (USER_ID, GAME_ID) VALUES (1, 3);
INSERT INTO PUBLIC.USER_GAME (USER_ID, GAME_ID) VALUES (1, 5);
INSERT INTO PUBLIC.USER_GAME (USER_ID, GAME_ID) VALUES (1, 8);
INSERT INTO PUBLIC.USER_GAME (USER_ID, GAME_ID) VALUES (1, 6);
INSERT INTO PUBLIC.USER_GAME (USER_ID, GAME_ID) VALUES (1, 2);
INSERT INTO PUBLIC.USER_GAME (USER_ID, GAME_ID) VALUES (3, 3);
INSERT INTO PUBLIC.USER_GAME (USER_ID, GAME_ID) VALUES (3, 8);