INSERT INTO PUBLIC.USER (ID, PASSWORD, USERNAME, OPT_LOCK_VERSION, WALLET) VALUES (1, 'ted', 'ted', 0, 900.01);
INSERT INTO PUBLIC.USER (ID, PASSWORD, USERNAME, OPT_LOCK_VERSION, WALLET) VALUES (2, 'gre', 'gre', 0, 900.01);
INSERT INTO PUBLIC.USER (ID, PASSWORD, USERNAME, OPT_LOCK_VERSION, WALLET) VALUES (3, 'red', 'red', 0, 900.01);