INSERT INTO PUBLIC.USER (ID, PASSWORD, USERNAME) VALUES (1, 'ted', 'ted');
INSERT INTO PUBLIC.USER (ID, PASSWORD, USERNAME) VALUES (2, 'gre', 'gre');
INSERT INTO PUBLIC.USER (ID, PASSWORD, USERNAME) VALUES (3, 'red', 'red');